### ISSUE TITLE
Bug in com.activeandroid.query.Set

### ISSUE THREAD

**Issue by hellokent** [pardom-zz/ActiveAndroid#56] opened 2013-04-15 11:48 UTC
in line 95:

args[i] = mWhereArguments.get(i).toString();

It would be:

args[i + setSize] = mWhereArguments.get(i).toString();

**Comment by vonloxley** [comment] 2013-04-15 16:11
Duplicate of #43.

**Closed as completed** 2013-04-22 18:59 UTC
